apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashibank
  namespace: demo-ns
spec:
  selector:
    matchLabels:
      app: hashibank
  replicas: 3
  template:
    metadata:
      labels:
        app: hashibank
    spec:
      containers:
      - image: jamiewri/hashibank:0.0.3
        imagePullPolicy: Always
        name: hashibank
        args: ["-dev"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hashibank-svc
  namespace: demo-ns
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: hashibank
---
